Yelp/task_processing

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py
- import six.moves.queue
- add execution_framework.stop
- drop start_new_thread
=> execution framework cleanups

examples/async.py, task_processing/interfaces/runner.py, task_processing/interfaces/task_executor.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/runners/async.py, task_processing/runners/subscription.py, task_processing/runners/sync.py
This way each plugin can specify their own interface for tasks. I went with a "has-a" relationship here because I think that will give us the most flexibility when running tasks.
=> TaskConfig is now a property of the TaskExecutor

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py
internal TASKPROC-25
add support for adding uris to the task config. This is used for pulling in the credentials for the docker registry, but I've kept it generic so that users aren't restricted to using it for only the docker registry.
=> add support for uris in task config

examples/async.py, examples/cluster/docker-compose.yaml, examples/promise.py, examples/subscription.py, examples/sync.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/integration/mesos/mesos_test.py
How does this work?
All the frameworks must use a role while registering with mesos. The framework will only use resources that belong to their role. Mesos will offer them resources with role * and their own role.
How do I know it works?
Ran all the examples and `make test`
=> Add support for mesos role in execution framework

task_processing/plugins/mesos/execution_framework.py
- retry behavior is in separate executor
- lower offer backoff
- don't immediately suppress offers upon framework initialization
=> drop retry behavior, add delay to offer suppression

examples/async.py, examples/cluster/playground/Dockerfile, examples/file_persistence.py, examples/promise.py, examples/subscription.py, examples/sync.py, itest, task_processing/executors/stateful/stateful_executor.py, task_processing/interfaces/event.py, task_processing/interfaces/persistence.py, task_processing/interfaces/task_executor.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/translator.py, task_processing/plugins/persistence/file_persistence.py, tests/mock_plugin/__init__.py, tests/unit/interfaces/retrying_executor_test.py, tests/unit/plugins/mesos/mesos_executor_test.py
- Added locks to execution framework
- Converted blacklisted_slaves and task_metadata from python dictionaries to pyrsistent pmaps
- Manual testing to check locks acquire and release
- Manual testing to check that persistent data structures are being re-set appropriately after changes
- Ran itest in examples
- As per discussion with jolynch and sagarp, previous attempt using a function to metaclass data structures to enforce thread safety would not work as intended. In order to control race conditions, I made the above changes.
- Future developers on this code will need to be wary of the locked contexts, unfortunately.
=> Kawaiwan make thread safe

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/translator.py, task_processing/runners/sync.py
- build docker parameters in exec framework
- cleanup leftovers of retry behavior in exec framework
- lock task retries map in retrying exec
- add logging to retrying exec
- cleanup task retries map after task is finished
- add success field to TASK_FINISHED event translator
- drop verbosity of sync runner
=> Fixes to exec framework, retrying exec, sync runner

Makefile, requirements-dev.txt, setup.py, task_processing/metrics.py, task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/mesos_executor_test.py, tox.ini
- Added metrics to execution framework
- Added tests for execution framework, including those that do not involve metrics
- Created and ran unit tests for metrics and rest of execution framework
- Ran itests from examples
- Metrics code is contingent on yelp_meteorite being present. If not, a mock object is returned so that calls to counters or timers do not break.
- Changes do not yet include a way to optionally install yelp_meteorite (or mock)  as the dependency_links option in setuptools was deprecated. An extra requirements file for Yelp dependencies might be required instead, as Paasta does it.
=> Kawaiwan add execution metrics

task_processing/interfaces/event.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/translator.py, task_processing/runners/async.py, task_processing/runners/sync.py, tests/unit/interfaces/event_test.py, tests/unit/plugins/mesos/mesos_executor_test.py, tests/unit/plugins/mesos/translator_test.py, tests/unit/plugins/persistence/dynamo_persistence_test.py
this is naive implementation of control events. they share the same datastructure as task events and some fields. we need them because we need a way to do controlled crash-landing in case of unrecoverable incidents (like framework being remvoed from mesos).
LF discussion on implementation details
https://github.com/Yelp/paasta/pull/1325 is blocked on this
=> control events

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/mesos_executor_test.py
lets avoid the situation where offers arrive before user is done with constructing the task configs
=> add an option for initial decline delay

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
blacklist the agent until the maintenance window is completed.
this rearchitects each blacklisted slave to have a separate thread
responsible for taking the node out of the blacklist, rather than a single
blacklist thread responsible for managing all blacklisted agents.
=> blacklist agents with upcoming maintenance window

task_processing/plugins/mesos/__init__.py, task_processing/task_processor.py
one use case - paasta needs to pull task config interface from MesosExecutor class which is much easier with this pr
=> expose executor classes from plugin registry directly

task_processing/interfaces/event.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/retrying_executor.py, tests/unit/plugins/mesos/execution_framework_test.py
factory on task_config event field was coercing all PMap descendants to actual PMap instances, losing task_id property from MesosTaskConfig class
also minor fixes to locks and filtering of non-task events in retrying executor
=> fix event task_config and retrying executor

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/execution_framework_test.py
To run GPU jobs via taskproc, we ideally should use mesos containerizer, which we currently do not support. As such, I have:
- Added gpus as a resource
- Added a containerizer option to MesosTaskConfig
- Changed the config sent to Mesos to use either mesos or docker containerizer
- make test
- Sync run on norcal-devc to a gpu instance (role isolated); cmd runs a script that uses pytorch to check for gpu availability.
- (DONE) ~~Mesos 1.3.0 has a [bug](https://issues.apache.org/jira/browse/MESOS-7692) in which env vars are not properly set in docker containers, which causes any gpu scripts to not be able to see gpus. The bug has been resolved but its patch has not been released, so @nhandler is working on applying the patch directly.~~
- To make gpu runs fully functional, mesos-slaves will …
=> Add gpu resource and mesos containerizer option

task_processing/utils.py, tests/unit/utils_test.py
- Added a util func to get mesos master (or any cluster master) from a services file
- make test
- Manually run the func to get the address
- Tried to exclude as much Yelp-y info as possible, but the default is still our own services file location
=> Add mesos master smartstack discovery as util

task_processing/plugins/mesos/execution_framework.py
The number of SignalFx time series keeps growing because paasta_remote_run includes a time stamp and a randomly generated ID in framework names. This patch drops both when creating metrics dimensions.
=> Reduce the number of signalfx time series with limited framework name

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
While making puppet changes, I realized I hadn't properly updated the gpus resource checks and the tests weren't catching it. This PR fixes that.
- make test (right and wrong cases)
- end-to-end run with gpu instance (mesos-slave started by modified puppet)
- This error does not affect anyone not using gpus
=> Fix gpus resource check and update tests

task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/execution_framework_test.py
- change gpus from floats to int in task config
- tox
- end-to-end test (ensure mesos accepts ints not floats)
- after feedback from related paasta PR
=> Change gpus from float to int

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py, tox.ini
I think it is better to re-enqueue the task in execution_framework than doing it in retrying_executor because not all applications have to use retrying_executor. This is something that execution framework should be able to deal with.
=> Deal with TASK_LOST due to invalid offers

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
Currently, we are not honoring ports field in task_config. Users can pass more than one port to map, but we are mapping 8888 internal port to one of the available ports. This can be fixed in another review.
=> Discard offers with 0 ports

examples/cluster/docker-compose.yaml, examples/cluster/mesos-agent-secret, examples/cluster/mesos-secrets, examples/cluster/mesos-slave-secret, tox.ini
This PR builds upon #60 to rename `slave` terminology to the canonical `agent` form (see [MESOS-1478](https://issues.apache.org/jira/browse/MESOS-1478) for context). 
I have not changed the scheduler code itself.
=> Rename slave to agent

examples/sync.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/mesos_task_config_test.py
This is TASKPROC-78. Mesos containerizer with Docker image support has been completed for the GPU work. This is to support running a command directly in a mesos containerizer.
=> Support mesos containerizer without an image

README.md, examples/README.md, examples/async.py, examples/cluster/docker-compose.yaml, examples/dynamo_persistence.py, examples/file_persistence.py, examples/hello-world.py, examples/promise.py, examples/subscription.py, examples/sync.py, itest, setup.py, task_processing/plugins/mesos/execution_framework.py, task_processing/runners/async.py, task_processing/task_processor.py
I did a few things here to make this repo a little more approachable:
+ Preferred `taskproc` as the canonical shorthand for Task Processing
+ Tidied up README and added a little more detail
+ Miscellaneous grammatical fixes.
+ Added a super simple annotated "hello-world" example.
+ Added all examples to itest except for promise (which doesn't appear to be implemented) and dynamodb (which I presume requires an external service to be running).
Still to do (in a separate pull request):
+ dynamodb_persistence should be dynamo_persistence (or we should rename the example and the test file to match)
+ We should pin to a specific version of PyMesos in our requirements.txt (this is unlikely / should not conflict with applications' own dependencies)
=> Making the repo more newbie friendly

.coveragerc, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/mesos_task_config_test.py
- make cmd mandatory
- disallow empty cmd
=> stricter checks on task config cmd attribute

examples/common.py, examples/timeout.py, task_processing/plugins/mesos/__init__.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/timeout_executor.py, tests/unit/interfaces/timeout_executor_test.py
I had to prefix the example test command sleep with dumb-init. Otherwise, TASK_KILLED took 120 seconds because SIGTERM was not delivered to the sleep process and we use 120 seconds as mesos agent docker_stop_timeout.
=> TimeoutExecutor

task_processing/plugins/mesos/execution_framework.py, task_processing/runners/async.py, task_processing/runners/subscription.py, task_processing/runners/sync.py, tests/unit/plugins/mesos/execution_framework_test.py
This PR is to deal with launchTasks failures. 
If launchTask() fails, then there 2 outcomes:
1) Mesos has received the task.
2) Mesos did not receive the task.
The current approach is to move the tasks into unknown state and reconcile their status periodically. If the tasks have been received by mesos, then it will return their current state. But, they were never received by mesos, then it is our responsibility to re-enqueue these tasks.
=> Deal with launchTasks failures.

task_processing/plugins/stateful/stateful_executor.py
Tested with examples/dynamo_persistence.py with a wrong table name.
=> Catch stateful_executor exceptions to keep events flowing

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
This fixes TASKPROC-129. 
Another way to fix it is to merge blacklisting with the background thread. I am keeping the original design to make the processing simple at the cost of one sleeping thread for each blacklisted agent.
=> Fixed the exception when an agent being blacklisted more than once

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
Tests on norcal-devc show /master/api/v1/scheduler hits are reduced a lot.
=> Decline offers in batch, fix reconciliation with 300s interval

examples/retry.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/stateful/stateful_executor.py, task_processing/runners/async.py, tests/unit/plugins/mesos/retrying_executor_test.py
Add retrying executor at examples/retry.py
Modify retrying executor to allow user passing params through task_config like this:
task_config = TaskConfig(
image='docker-dev.yelpcorp.com/dumb-busybox',
cmd='/bin/false',
retries=5,
retry_pred='lambda e: not e.success'
)
Manually testing by command 
"docker-compose -f examples/cluster/docker-compose.yaml run playground examples/retry.py"
=> Add retrying executor example and pass params on task_config

README.md, examples/retry.py, examples/timeout.py, itest, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/retrying_executor.py
1. Fix incorrect retrying log message
2. Make the field "retries" truly the number of retries, not the total number of runs (retries+1).
=> Fixed retry logging and retries counts

task_processing/plugins/mesos/logging_executor.py
TASKPORC-155 happened because the logging executor trying to fetch the last piece of log while the task was never added to the running_task map.
=> Only fetch the last piece of logs when the task is active

examples/offer_timeout.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/task_config.py, tests/unit/plugins/mesos/execution_framework_test.py
adds a per-task offer timeout.
I also moved the mesos task config into its own module, since it was bugging me how big execution_framework was getting (I've got more for this, but its a start)
=> Support offer timeout

examples/promise.py, task_processing/runners/promise.py
`Promise.run()` returns `concurrent.futures.Future`.
The new version of `examples/promise.py` is adapted from `examples/sync.py`, as the current version of `examples/promise.py` seems to be quite outdated.
=> Implemented Promise task runner

task_processing/plugins/mesos/task_config.py
Set default value for `offer_timeout` to 60 seconds to prevent errors like
```
Exception in thread Thread-1:                                  
Traceback (most recent call last):                             
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 92, in __getattr__                     
return self[key]                                           
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 68, in __getitem__                     
return PMap._getitem(self._buckets, key)                   
File "/opt/venvs/paasta-tools/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 65, in _getitem                        
raise KeyError(key)                                        
KeyError: 'offer_timeout'
```
While …
=> Set `offer_timeout` to 60sec by default to prevent an exception

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/retrying_executor.py, tests/unit/plugins/mesos/retrying_executor_test.py
- pass task config in offer timeout event
- move kind=task filter in retrying executor to the top of the loop
=> fix couple issues with events missing required attributes

task_processing/interfaces/event.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/translator.py, tests/unit/interfaces/event_test.py, tests/unit/plugins/mesos/translator_test.py, tests/unit/plugins/persistence/dynamo_persistence_test.py
When event kind is 'task', we need to make a subset of attributes mandatory, which is not possible to do with per-field invariants.
=> add global event invariant

task_processing/plugins/mesos/task_config.py, tests/unit/plugins/mesos/mesos_task_config_test.py
fail when trying to create task config with id >255 chars
=> task config id length invariant

task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/mesos_executor.py
I want to be able to direct messages for each task to a different file, and Python logging seems like the best way to do that. Here's an idea for how to add that functionality to the logging executor.
Very open to other ideas on how to achieve this. Maybe it would be better to create subclasses of LoggingExecutor that implement setup_loggers, etc?
=> Add option for logging executor to use python logging

.activate.sh, .deactivate.sh, .gitignore, Makefile, examples/cluster/docker-compose.yaml, examples/cluster/playground/Dockerfile, requirements-dev.txt, requirements.txt, setup.py, task_processing/interfaces/persistence.py, task_processing/interfaces/runner.py, task_processing/interfaces/task_executor.py, task_processing/metrics.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/timeout_executor.py, task_processing/plugins/stateful/stateful_executor.py, task_processing/runners/async.py, task_processing/runners/subscription.py, task_processing/runners/sync.py, task_processing/task_processor.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/retrying_executor_test.py, tox.ini
This commit strips out six from taskproc -- there's nothing that's using taskproc on Python2.7 and Python2.7 is basically EOLed anyways, so let's not bother.
I also clean up the development environment/tox/etc a little bit here.
=> clean up dev/tox/etc, strip out six (we only support 3.6 from now on)

.gitignore, examples/cluster/playground/Dockerfile, mypy.ini, requirements-dev.txt, task_processing/metrics.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/resource_helpers.py, tests/unit/plugins/mesos/conftest.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/resource_helpers_test.py, tox.ini
This change does the following:
* _actually_ use python3.6 in the examples Docker container; in my last request I just installed it, but all the scripts were still using python3.5
* bumps max line length to 100; there are so many long imports and things that we have to go through some pretty painful shenanigans to fit into 80 characters
* pulls out and DRYs up code around handling resource offers: this makes it more extensible and will get re-used when I create the pod executor
* changes the logic around how ports are handled; instead of passing around range() objects for all the ports that are available, we just pass a (begin, end) pair, which we update every time a port gets used
* some initial mypy support
=> pull out offers and resources into another file

.gitignore, task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
`get_tasks_to_launch` removes task from the queue to prepare it for launch. if `kill_task` is called during that time - task metadata will be removed which will cause an exception.
let's wrap to chunk from `get_tasks_to_launch` and until we get a response from driver in a lock so nothing will interrupt and mess with the metadata in between.
=> [fix] Killing task during get_tasks_to_launch will cause exception

examples/async.py, examples/dynamo_persistence.py, examples/file_persistence.py, examples/hello-world.py, examples/offer_timeout.py, examples/promise.py, examples/retry.py, examples/subscription.py, examples/sync.py, examples/task_logging.py, examples/timeout.py, task_processing/plugins/mesos/__init__.py, task_processing/plugins/mesos/constraints.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/mesos_pod_executor.py, task_processing/plugins/mesos/mesos_task_executor.py, task_processing/plugins/mesos/metrics.py, task_processing/plugins/mesos/resource_helpers.py, task_processing/plugins/mesos/task_config.py, task_processing/plugins/mesos/translator.py, task_processing/task_processor.py, tests/unit/plugins/mesos/conftest.py, tests/unit/plugins/mesos/execution_framework_test.py, tests/unit/plugins/mesos/mesos_executor_test.py, tests/unit/plugins/mesos/mesos_task_config_test.py, tests/unit/plugins/mesos/mesos_task_executor_test.py, tests/unit/plugins/mesos/resource_helpers_test.py, tests/unit/plugins/mesos/retrying_executor_test.py, tests/unit/plugins/mesos/translator_test.py
This change pulls some logic out of the execution framework into the executor, in preparation for pods support.  To support having different executor objects for pods and non-pods, the MesosExecutor now expects a set of callbacks to be passed in to describe how to handle various pod/task use cases.  I created two subclasses of `MesosExecutor` which fill in these callbacks appropriately for "bare" tasks and pods (actually the pods executor is not implemented yet).
Currently we just support task creation and handling Mesos updates; we will also need to handle killing tasks, but in order to support that I'm going to want to move the task_metadata field from the execution framework into the executor.  That's going to be a bigger change so I'm going to put up a separate review for that once …
=> handle offer response by the MesosTaskExecutor instead of the ExecutionFramework

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/mesos_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/timeout_executor.py, tests/unit/plugins/mesos/execution_framework_test.py
Let me know what you think about this approach of adding a method to wrap calls to the driver.
I also want to add feedback in the executors if kill_task returns False (i.e. it failed), ~~haven't gotten around to it yet.~~ Added this too.
=> Catch all exceptions when calling driver

task_processing/plugins/mesos/execution_framework.py
Internal ticket TASKPROC-209
Stack trace indicates that the keys in task_metadata are changing as we iterate over it.
```
Exception in thread Thread-5:
Traceback (most recent call last):
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/opt/venvs/jolt/lib/python3.6/site-packages/task_processing/plugins/mesos/execution_framework.py", line 178, in _background_check
task_id in self.task_metadata
File "/opt/venvs/jolt/lib/python3.6/site-packages/task_processing/plugins/mesos/execution_framework.py", line 179, in <listcomp>
if self.task_metadata[task_id].task_state is not
File "/opt/venvs/jolt/lib/python3.6/site-packages/pyrsistent/_pmap.py", line 68, in …
```
=> Access metadata for reconciliation inside lock

task_processing/plugins/mesos/logging_executor.py, tests/unit/plugins/mesos/logging_executor_test.py
The task_id may not be in `self.staging_tasks` if we have restarted and are receiving reconciliation events. We want the thread to continue processing events. Also added some tests for the logging executor.
I wanted to fetch logs again, but given the TASK_RUNNING update only has the agent_id, it doesn't seem possible to get the agent_url back. (We don't have the master url anywhere, to get the agent url from the agent id.) This is an example of the update:
```
{
'agent_id': {'value': '2bd4b611-9206-47ca-a64d-7b7a2973b9e0-S1'}, 
'container_status': {
'container_id': {'value': '...'}, 
'network_infos': [{
'ip_addresses': [{'ip_address': '169.254.0.1', 'protocol': 'IPv4'}]
}]
},
'data': '...', 
'executor_id': {'value': 'MASTER.test.1.first.930ec85b-10a5-43e9-8970-05fee5a1d247'}, 
'labels': …
```
=> Don't raise exception if running task is missing

task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/retrying_executor.py, task_processing/plugins/mesos/timeout_executor.py, tests/unit/plugins/mesos/retrying_executor_test.py, tests/unit/plugins/mesos/timeout_executor_test.py
- Update timeout and retrying executors to allow missing tasks to reregister during reconciliation
- For the timeout executor, if it now encounters a non-terminal task update that the executor doesn't know about, it will add the task to its list of running_tasks using the update's timestamp as a baseline from which to establish a timeout deadline.
- For the retrying executor, if it now encounters a task update that the executor doesn't know about, it will similarly add the task to its list of task_retries and assumes the update's attempt number is the number of attempts so far.
- The above 2 points are a consequence of needing to pull information that is lost unless we can somehow recover task histories (like when a task started).
- make test
=> Modify timeout and retrying executors to allow missing tasks to reregister during reconciliation

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
this deals with a condition where a task has no entry in the task
metadata map. we don't want to crash the main thread in response, so we
just log
=> deal with missing task metadata more gracefully

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/metrics.py, tests/unit/plugins/mesos/execution_framework_test.py
- move per-task logic out of `_background_check` into `_background_check_task`
- log timing information for each bg check run
=> Split execution framework background check

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
- no `continue` near :616 would result in both declined and accepted log messages
- create missing timer metric (line 434)
- change formatting to f-strings (the rest)
=> Fix incorrect log message when offer is declined and missing metric in execution framework

setup.py
The failover stuff (startign in taskproc 0.0.17) is only in pymesos 0.2.14 and up.
=> now require min version of pymesos

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
tzhu made this suggestion, apparently it improves jolt cpu usage by 10%:
```
status quo: 32:32min CPU in 48min (0.677 cpu)
optimized: 8:00~8:15min CPU in 15min (0.541 cpu)
```
I checked the other places we call get_metric, nothing else obvious to optimize.
=> Only get_metric for insufficient offer once

task_processing/interfaces/event.py, task_processing/interfaces/task_executor.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/resource_helpers.py, task_processing/plugins/mesos/task_config.py, task_processing/plugins/persistence/dynamodb_persistence.py, task_processing/task_processor.py, tests/unit/plugins/persistence/dynamo_persistence_test.py
- Currently, the DynamoDB persister persists both task and control events. The problem is that control events do not `task_id`s, but our DynamoDB tables expect them.
- In this change, I made it so that we do not persist control events, only task events.
- manual testing on a dev paasta master
- make test
- Error when persisting control events: https://gist.github.com/kawaiwanyelp/886819f047a1785e3e823a8771100ff6
- This change also includes a bunch of changes to silence or fix mypy errors. 
- pyrsistent seems to be bugged in that `PMap`s and `PVector`s do not seem to play well with mypy. Hence, I've instructed `mypy` to ignore them using `# type: ignore`
=> Stop dynamodb persister from persisting control events

task_processing/interfaces/event.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/logging_executor.py, task_processing/plugins/mesos/resource_helpers.py, task_processing/plugins/mesos/task_config.py, task_processing/plugins/mesos/translator.py, task_processing/task_processor.py, tests/smoke_test.py, tests/unit/interfaces/event_test.py
- I previously added "type: ignore"s since pyrsistent didn't have good type annotations. Now that they have, I have removed them and put in type annotations for task_processing.
- I use TYPE_CHECKING because not using it in the way I do causes tests to fail even if mypy checks pass.
make test
- In #135, @vkhromov advocated for strict type annotations. However, I had a lot of trouble doing so for Mesos things like Offers that we use via duck typing. Mesos does not provide type annotated interfaces we can use to type them, so I'd have to use `Any`. I think removing the ignores for now is sufficient. If anyone wants REALLY strict type annotations, please comment.
=> Remove type ignores since pyrsistent now has passable type annotations

task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/mesos_executor_test.py
The driver exits on things like HTTP error codes or parsing errors. I think it makes sense to reconnect in these cases, instead of letting the execution framework continue when the driver thread has stopped.
example of the driver exiting: https://github.com/douban/pymesos/blob/master/pymesos/process.py#L162
=> Restart driver if it exits for any reason

requirements-dev.txt, tox.ini
I love running the latest versions of everything as much as the next person, but the latest version of mypy is much more strict and understanding than our codebase currently allows.
I would like to start by pinning first to get the build green, then improving our annotations and upgrading mypy in a different PR.
=> Pin mypy to get a stable build

task_processing/plugins/mesos/logging_executor.py
@qui theorized that getting logs can get super behind if we are requesting logs from a series of downed hosts since we don't have a timeout set. To fix that, this review adds a timeout (as all production code should) to the logging executor's requests.
only `make test`
This case we are addressing is hard to simulate since we need a series of downing hosts. I'll test this in a staging environment before rolling it out all the way.
=> Add timeout to requests in logging executor to prevent hanging

examples/cluster/playground/Dockerfile, task_processing/plugins/mesos/constraints.py, tests/unit/plugins/mesos/constraints_test.py, tox.ini
(COMPINFRA-333) We have a "stable" pool and a "stable_batch" pool, and
jobs that are supposed to run on the "stable" pool are getting scheduled
on the "stable_batch" pool because the constraint is too open. This
change should make it so that stuff only gets scheduled on the pool they
specify.
(deleted coverage because it's broken in Python 3.6.0)
=> Make the LIKE constraint a "full match"

Makefile, requirements-dev.txt, tox.ini
* Pin hypothesis since otherwise running tests on xenial boxes will fail
* Use system tox + pass indexserver to tox as an env var
=> Pin hypothesis + use system tox + fix makefile/tox.ini

README.md
We no longer use Travis, so we might as well get rid of the badge :)
=> Remove TravisCI badge from README

.github/workflows/ci.yml, .github/workflows/pypi.yml
Our previous config made it so that only PRs made from a branch on this
repo would get tested - so anyone creating a PR from their fork would
not get their changes tested automatically.
Additionally, add back in the config to upload to PyPI since Tron will 
need to pick up these builds for GH Actions.
=> Enable GH Actions for all PRs + upload to PyPI

setup.py, task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kube_client_test.py, tox.ini
Much like in paasta-tools, we want to ensure that anything talking to
the k8s API has loaded the correct kubeconfig so that it knows what
master to talk to as well as what user/certs to use.
=> Add a KubeClient class

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/utils.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
We'll use this in the same way as we handled things in the mesos plugin:
run/kill will direfctly mutate the task_metadata member I'm adding in this PR
and we'll eventually have the thread(s?) that handle watching Pods also
add to this member in addition to the event queue that we'll share with
Tron
=> Add a way to track task metadata in k8s plugin

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
This also adds in `namespace` as a required parameter for creating a k8s
executor instance.
=> Teach k8s plugin how to kill a Pod

requirements-dev.txt, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/mesos/task_config.py, task_processing/plugins/mesos/translator.py
We pinned mypy ~2 years ago, but this means that we can't use certain
new-ish typing features such as the TypedDict backport in
typing-extensions.
I've unpinned mypy and added `# type: ignore` comments to all the
existing typing violations as they're all pyrsistent-related (which
makes sense since I doubt the typestubs for pyrsistent handle all
possible use-cases)
=> Unpin mypy

setup.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/types.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
We'll have two threads: one that simply tails a k8s stream of Pod events
and places these into an internal queue and a second one that takes
these events and (potentially) converts them into task_processing Events
and/or takes some form of action on them (e.g., removing a Pod from the
plugin's task_metadata data structure)
For now the thread that creates Events is mostly just a stub though.
=> Add skeleton of Pod event processing

setup.py
Without this, mypy won't attempt to use our inline types when we're included
as a dependency.
I also moved us away from `include_package_data=True`, as I don't really
think it's worth having a `MANIFEST.in` file for adding datafiles when we
can just do it inline in our `setup.py`.
Additionally, I removed examples from our packaging since those are only
useful when people are playing around with `task_processing` development.
For more info on `py.typed`:
[PEP](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)
[mypy docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages)
=> Make task_processing PEP-561 compatible

task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kube_client_test.py
The file is generally called a kubeconfig file, so we should be
consistent with that
=> Rename kube_config_path to kubeconfig_path

task_processing/plugins/kubernetes/types.py
Much like in the Mesos plugin, we're going to try to track the different
states that a task can be in - and to do this, we need to expand our
enum for the potential set of states for a k8s task
=> Add additional task states to KubernetesTaskState

task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py
We regualrly rotate certificates in our clusters and the k8s clientlib
won't notice when these files change (nor does it have a way to add a
hook on a 401), so manually catch any 401 API exceptions and reload the
kubeconfig file.
=> Handle certificate expiry in k8s plugin

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
We'll use these in Tron in order to transition a task between the
various states in Tron's state machine
=> Start translating k8s events into task_processing ones

task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py
We'll need these for:
* resource limits: to isolate resource usage per-task as we did in Mesos
* capabilties: to match the security status-quo in PaaSTA/Tron-on-Mesos
* volumes: to allow people to mount files on disk :p
* environment variables: we'll need these for both PaaSTA secrets as
well as for normal usage (some tasks may configure
themselves/libraries with environment variables)
=> Add resource limits, caps, env vars, and volumes to k8s task_config

task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py
We now implicitly call get_sanitised_kubernetes_name() when returning
pod names so that we don't need our users to do this.
This change does mean that `name != pod_name.split(".")[0]`, but this
should be fine
=> Ensure that k8s pod names follow yelp conventions

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
in #168 , we duplicated some paasta implementation within task-proc to set up secrets in envvars.  
This wasn't going to be maintainable moving forward, so we've removed that and task_proc will simply be passed a new `secrets_environment` config specifying the name of the envvar and the required `V1SecretKeySelector` values necessary to pull from a `V1Secret`.
This makes task_processing code much cleaner and straightforward.
=> TASKPROC-249: Revert duplication of paasta logic, pass secret refs directly

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
Just like pods, containers have restrictions on what their names can be.
=> Sanitise k8s container names

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
Unfortunately, we won't be able to use the `name` attribute from
KubernetesTaskConfig to name containers as we were planning due to the
63char length limit on DNS label names - but it turns out that we don't
actually need these for anything (we initially thought our log routing
system used these names), so we'll stick with "main" for now until
there's a usecase that requires something more dynamic
=> Hardcode k8s container names

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/types.py
I made a typo in the original PR added task events and somehow added an
all-caps platform_type.
Additionally, this change adds a TASK_LOST status and uses that instead
of TASK_UNKNOWN when we recieve a Pod event with a phase of Unknown
since we'll be using TASK_UNKNOWN as the initial state when we're
starting up with pre-existing state (e.g., after a Tron restart)
=> Fix k8s failed platform_type casing + add TASK_LOST

task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
In https://github.com/Yelp/Tron/pull/822/files we decided to use `secret_name` as the key that held the name of the Kubernetes V1Secret resource we were using as a source for our envvars, rather than `secret`. This should minimize confusion since this field does not store any secrets itself, just the name of the secret resource.
This change updates the schema/code/tests to reflect this change.
=> Fix k8s secret source definitions to use secret_name instead of secret

task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kube_client_test.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
In order to handle tron restarts, we will need to first pass kubernetes_pod_executor a list of KubernetesTaskConfigs from our saved state.
We initialize this in `kubernetes_pod_executor` upon init, filling `task_metadata` with UNKNOWN KubernetesTaskStates for each pod name to speed up initalization.
Reconciliation with said pods will then happen in `reconcile()`, where we will check the state of the pod we are attempting to reconcile with the Kubernetes API, then re-use the exact same logic to set TaskState (etc) as when we handle `PodEvents` based on pod phases.   This required splitting out said logic into two new helpers, `__update_deleted_pod` and `__update_modified_pod` so they could be used for both usecases.
=> TASKPROC-244:  Initialize metadata via state data and implement reconcile for k8s

task_processing/plugins/kubernetes/kube_client.py, tests/unit/plugins/kubernetes/kube_client_test.py
When I added `KubeClient.get_pod` in #175, instead of passing an f-string of the pod name, I passed a set of `{pod_name}` to `read_namespaced_pod`.
This also exposed that there was no validation that we were calling `read_namespaced_pod` with correct arguments, so I added a test for this, which would have caught this typo earlier.
```
E       AssertionError: Expected call: read_namespaced_pod(name='pod-name', namespace='ns')
E       Actual call: read_namespaced_pod(name={'pod-name'}, namespace='ns')
```
=> Fix typo in KubeClient.get_pod

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/task_metadata.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
This PR adds node selectors and affinities to the k8s task config, and makes the pod executor use them. Couple of things:
- By default, it does not add any selectors or affinities. If we want to set, say, a default selector for the default pool, that should be set upstream.
- In soa-configs, node selectors and affinities are exposed to users as just node selectors. In task_processing, they are kept separate. The assumption is that the soa-configs interface has already been transpiled to selectors and affinities upstream.
- I moved the task metadata stuff to its own file because it was royally screwing with typing imports.
`make test`
no real-world test yet, but i am reasonably confident this works, since this is exactly how paasta does it. ill still do a test before merging, but the PR is …
=> Add node selectors and node affinities

task_processing/plugins/kubernetes/task_config.py
The way that Tron config works, lists often get turned into tuples. The
k8s clientlib doesn't seem to mind that it's getting tuples here, so we
might as well allow them to be passed in in the first place so that our
users (or us in Tron) don't need to care about tuples vs lists in the
first place here.
=> Allow node affinity values to be wrapped in tuples

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
This is what is recommended by our internal security team, so let's just
hardcode for now since we *shouldn't* really need any of the other
policies.
=> Hardcode the DNSPolicy for Pods to Default

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
We'll need this to adhere to the PaaSTA Workload Contract (and allow
tooling like OPA to work with our Pods)
=> Support setting Pod labels

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py
We'll use this for Pod Identity - there's a webhook that will inject
a secret token + some environment variables if a Pod has a Service
Account set up.
=> Add Service Account support

examples/cluster/playground/Dockerfile
pypa.io now serves a get-pip that requires a newer python than what we
test with by default - unless you specify a versioned path
=> Use versioned get-pip for OSS Dockerfile

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
These are needed for our Spark work as well as for fulfilling the PaaSTA
workload contract
=> Enable setting env vars using field selectors

tests/unit/plugins/mesos/timeout_executor_test.py
This was causing some test pollution in tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py::test_process_event_enqueues_task_processing_events_pending_to_running as the mocked value isn't a float, besides the fact that it should have been restored
=> Fix time.time mocking

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py
Allow the user to run more than one container in the pod for a task. Since the pod and container configuration is pretty much all flattened in KubernetesTaskConfig, I've made additional containers addable by nesting KubernetesTaskConfig itself. Of course, none of the pod-level configuration will ever get applied in a nested KubernetesTaskConfig, and nesting more isn't supported (actually checked against). 
Right now, common environment/volume configs would have to be duplicated at the caller. I am not sure if doing something like automatically applying such configs from the main task config would make much sense (I think it would be a bit surprising). 
Another note is that the main container is still called "main", but containers specified via extra_containers need to be given a name via …
=> Specify other containers to run

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
Permit passing through `privileged` for V1SecurityContext. There exists a need to run a container image, [whose documentation insists it be run --privileged](https://github.com/docker-library/docs/tree/master/docker#start-a-daemon-instance).
We already support cap_add and cap_drop, but privileged also [does a bunch of other things, probably the most important of which looks to be mounting cgroupfs rw](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/moby/moby%24%40v20.10.17+HostConfig.Privileged&patternType=literal)
=> Permit passing through V1SecurityContext.privileged

task_processing/plugins/kubernetes/kube_client.py
It looks like when we reloaded previously, we only reset `self.core`, but re-used our initial `kube_client.ApiClient()` object.
As a result, we continued to use the auth config tied to the first client even on reload. 
This will make sure we recreate self.api_client when we reload kubeconfig as well.
=> TRON-1777: fix reloading kube config on token expiration

.github/workflows/ci.yml, .github/workflows/pypi.yml, .pre-commit-config.yaml, README.md, examples/cluster/playground/Dockerfile, requirements-dev.txt, setup.py, task_processing/task_processor.py, tests/unit/plugins/persistence/dynamo_persistence_test.py, tox.ini
The reason for adding `@settings(suppress_health_check=(HealthCheck.function_scoped_fixture,))` was due to the warning below.
```
E       hypothesis.errors.FailedHealthCheck: Function-scoped fixture 'persister' used by 'tests/unit/plugins/persistence/dynamo_persistence_test.py::test_replaces_decimals_list'
E       
E       Function-scoped fixtures are not reset between examples generated by
E       `@given(...)`, which is often surprising and can cause subtle test bugs.
E       
E       If you were expecting the fixture to run separately for each generated example,
E       then unfortunately you will need to find a different way to achieve your goal
E       (e.g. using a similar context manager instead of a fixture).
E       
E       If you are confident that your test will work correctly …
```
=> Upgrades venv and tests to python 3.8

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
If you try to launch a kubernetes pod with command=`/bin/bash` it will exit immediately. I am working out how to use `paasta local-run` to run an interactive pod on the cluster, and this is a first step in that direction.
Plumb through the `stdin`, `stdin_once`, and `tty` flags for the [V1Container](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Container.md)
=> Support stdin and tty flags to support launching pods with commands like /bin/bash

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
Resource requests are currently not explicitly set - this results in k8s setting
the memory/cpu/disk requests to the same value as the limit.
For the most part, this is desired behaviour at Yelp as the main consumer of this
library is Tron and we don't expect our batches to need to "burst" any of these
resources. Additionally, we generally want to signal to k8s that our batches shouldn't
be killed if there are other (more interrupt-tolerant) workloads on an overloaded
node by defaulting the QoS class for any task_proc-created Pods to `Guaranteed`
precisely by setting `requests = limits`.
However, one of our other large task_proc workloads (Jolt) would like to have 
control over the requests as their workload runs in an isolated pool and cannot (at
least at the moment) be easily …
=> Add support for overriding resource requests

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
For PaaSTA services, we have support for mounting Kubernetes Secrets as
files directly - this adds similar support for anything launched by
task_processing.
For Tron usage, we're expecting paasta-tools to deal with formatting all
the information that we need here and pass it to Tron (which will then
just wrap it in a KubernetesTaskConfig)
=> Add support for file-based secrets

setup.py
Let's fix the dep-problem here rather than patching downstream :) 
context: https://yelp.slack.com/archives/C048HCBDD0U/p1686322172245599
=> Add typing-extensions as a k8s-specific dep

.github/workflows/ci.yml, .github/workflows/pypi.yml, task_processing/plugins/kubernetes/kubernetes_pod_executor.py
This PR currently contains: 
- handling of Added events
=> Handling Added events

task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py
There's two potential issues with our termination code:
1. we try to delete a Pod that no longer exists
2. we successfully delete a Pod, but k8s coaleses the event and task_processing/our caller doesn't see the termination event
Solutions:
1. return success on a 404 response to a delete - regardless of what happened, we're in the desired state :p
2. Send a synthetic event to our caller in kill() + fixup our internal state
=> Handle deleting deleted existent pods + send synthetic event on kill()

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/types.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
This is the equivalent of https://github.com/Yelp/paasta/pull/3859 in the land of task-processing.
I'll then proceed to implement the equivalent of https://github.com/Yelp/paasta/pull/3888 within Tron.
=> support projected service account volumes

task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
Just like https://github.com/Yelp/paasta/pull/3972 and https://github.com/Yelp/paasta/pull/3973, we need to ensure that
there are no duplicates between cap_add and cap_drop - otherwise,
the cap_drop entry will "win" and the duplicate capability will not be
added.
=> Only drop capabilities that are not added

task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
There was an edge case where sanitized pod names ending up with .<6 characters> would then get truncated to something like `.--<4 random chars>` due to our truncation logic in `get_sanitised_kubernetes_name`. 
However `.--aaaa` is not valid in a pod name as each section between `.`s must start with an alphanumeric character.
We saw errors such as the following when this case was hit:
```
{"reason":"FieldValueInvalid","message":"Invalid value: \"some-long-pod-name.--9b3a\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and
must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')","field":"metadata.name"}
```
Before we try to add our …
=> TRON-2333: Fix pod names ending in .--xxxx

task_processing/plugins/kubernetes/kubernetes_pod_executor.py
We've seen an increase in cases where the Watch (for a reason I don't quite understand yet - some of the things I've been reading suggest that there's maybe something re: k8s API caches and whatnot exipring) starts erroring out with exceptions like:
```
kubernetes.client.exceptions.ApiException: (410)
Reason: Expired: too old resource version: 1642912881 (1644329743
```
While in the past this seems to have generally always fixed itself with the pre-existing restart code, in the aforementioned cases we've seen this loop get stuck in a restart-loop that it we either never recover from until a human intervenes OR it takes long enough to recover that we start losing events.
This diff ensures that when we restart the watch loop, we restart as if we were starting a fresh Watch - this does mean …
=> Handle Watch expiration by resetting the resourceVersion

task_processing/plugins/kubernetes/kubernetes_pod_executor.py
We can't have exponential backoff if there's no base increase ;)
We should probably try to figure out a good way to write some tests for these infinite loop threads
=> Actually increment attempt counter in watch loop
