.travis.yml, Makefile, requirements.txt, tox.ini
- smaller makefile
- .tox/dev env instead of .taskproc
- move integration tests into tox
=> makefile stuff

examples/async.py, task_processing/interfaces/task_executor.py
immutable, type assertions, value checks
=> TaskConfig as PRecord

.pre-commit-config.yaml, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py
I have refactored the mesos scheduler to remove references to paasta and some other unnecessary stuff. @Rob-Johnson @keymone @jolynch please take a look :)
=> Simplify mesos scheduler and remove references to paasta.

task_processing/plugins/mesos/execution_framework.py
wrap task metadata into type-checked TaskMetadata precord
=> task metadata prec

task_processing/plugins/mesos/execution_framework.py
the code for building a task bothered me so i've cleaned it up and restructured to be less imperative. also the build_* functions are gone because they're now just single Dict() calls.
=> task building cleanup

.travis.yml, Makefile, requirements-dev.txt, tox.ini
This should cause Travis to attempt to upload tagged releases of task_processing to pypi.
=> Configure Travis to upload to pypi

examples/async.py, examples/subscription.py, examples/sync.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/mesos_executor_test.py
- shift credentials concern
- allow overriding framework kwargs in mesos executor
=> tweaks in credentials passing and mesos exec framework initialization

task_processing/plugins/mesos/execution_framework.py
Changes:
1. record task state transition
2. only kills stuck tasks in staging state;
Tests:
1. Long running task (>60s) won't be killed in devc cluster.
2. tox -e integration
=> Fixed task state update to avoid premature termination

task_processing/plugins/mesos/execution_framework.py
pymesos update.state is unicode, we need str
=> fix task state str typecheck

examples/sync.py, task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/mesos_executor_test.py
This is TASKPROC-52. examples/sync.py can run against a real cluster with "python examples/sync.py -s 8385iBfX5s2BrSh6eiG -r taskproc -p taskproc -m 10.40.5.5:5050". There are no confusing zero resource offers in the log any more https://pb.yelpcorp.com/286124 vs. https://pb.yelpcorp.com/286126.
=> Expose ExecutionFramework pool setting via MesosExecutor

examples/async.py, examples/file_persistence.py, examples/promise.py, examples/subscription.py, examples/sync.py, itest, itest.sh, tox.ini
- run sync, async and subscription in itests
- change sleeps to /bin/true
- exit with relevant status from examples
- run busybox in examples
=> useful itests

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
instead of log line per offer on each resourceOffer call which is quite spammy when there are lots of agents
=> aggregate offer outcomes and log once per resource offer

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
Added code to handle duplicate status updates from mesos. Also fixed a parameter mismatch in reregistered method in execution framework.
=> Added logic to deal with duplicate terminal status updates from mesos.

task_processing/plugins/mesos/execution_framework.py
Just logging the offerId for now. After some investigation, I will come up with a strategy to deal with this.
=> Add offerRescinded callback to mesos scheduler

task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/mesos_task_config_test.py
=> sensible factories for mesos task config fields

tests/unit/plugins/persistence/dynamo_persistence_test.py
- reuse event generator
- set average text and dict sizes
- reduce number of examples
=> speedup hypothesis tests

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
This change replaces the last state update timestamp with a {state: timestamp} map to keep track of task state transitions until a terminal state. 
I discarded a change earlier to enforce task execution timeout based on states in favor of a timeout executor. Still, expanding the last state to a set of states is useful in debugging because the stateful executor is not always used by all applications.
=> Keep track of task state history instead of the last state update

task_processing/plugins/mesos/execution_framework.py, task_processing/plugins/mesos/mesos_executor.py, tests/unit/plugins/mesos/execution_framework_test.py
=> support setting environment vars

setup.py
Updated this to a real email address.
=> Update email address in setup.py.

examples/async.py, task_processing/runners/async.py
=> Exit process when the asynchronous event handler excepts

task_processing/plugins/mesos/execution_framework.py
Manually tested and tests are passing
=> Exclude queued tasks from reconciliation

task_processing/plugins/mesos/execution_framework.py
This fixes the offer suppressing race condition in TASKPROC-149.
=> Put offer suppressing logic under the framework lock

task_processing/plugins/mesos/execution_framework.py, tests/unit/plugins/mesos/execution_framework_test.py
Manually tested
Added a unit test
=> Extend kill_task to remove queued tasks

task_processing/interfaces/event.py, task_processing/plugins/mesos/execution_framework.py, tests/unit/interfaces/event_test.py, tests/unit/plugins/persistence/dynamo_persistence_test.py
- make .raw attribute mandatory
- include .raw in offer timeout terminal event
- also reformat some code for readability
=> fix events without raw field

task_processing/plugins/mesos/execution_framework.py, task_processing/task_processor.py
This is to deal with leader re-election. It does not hurt on normal conditions.
=> Always suppress incoming offers when task queue is empty

tests/unit/runners/async_test.py, tests/unit/runners/promise_test.py, tests/unit/runners/subscription_test.py, tests/unit/runners/sync_test.py
Some sanity checks, fixes the build.
=> Basic tests for runners

task_processing/plugins/mesos/translator.py, tests/unit/plugins/mesos/translator_test.py
=> Inject a MESOS_TASK_ID variable for services to use

task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_utils_test.py
We'll use these soon in order to create a PodSpec with all the necessary
execution-related bits
=> Add helpers for creating Pod/Container metadata

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, task_processing/plugins/kubernetes/task_config.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
These are exactly the same as what we do in PaaSTA.
=> Set additional security-related Pod settings

task_processing/plugins/kubernetes/kubernetes_pod_executor.py
If a Pod exits quickly enough, kubernetes will compact the running +
finished events into a single finished event. This messes up the Tron
state machine as it assumes that if a `done` transition happens on a
pending task, then that task failed to start.
We can remediate this by ensuring that we send out a `running` event if
task_proc has not processed a running event by the time it sees a finish
one.
=> Emit running event if k8s compacts one away

task_processing/plugins/kubernetes/task_config.py, task_processing/plugins/kubernetes/utils.py, tests/unit/plugins/kubernetes/kubernetes_task_config_test.py
We don't appear to be anywhere near this limit, but might as well
future-proof while we can
=> Truncate long pod names

task_processing/plugins/kubernetes/kube_client.py, task_processing/plugins/kubernetes/kubernetes_pod_executor.py
https://jira.yelpcorp.com/browse/TRON-1743
set custom user agent for k8s client usage from tron/task_proc
Adding an argument user_agent to class KubeClient so that we can specify this from the caller.
=> Adding an argument user_agent to Kubeclient

task_processing/plugins/kubernetes/kubernetes_pod_executor.py
Some consumer is interested in a particular container's change in state after #194. These are sent as pod modified events since the other containers are still running. Such events are currently ignored since they don't result in a pod state transition, but if there are multiple containers, then it stands to reason for individual container state transitions to be something a caller could want to find out about.
=> Make it possible to receive all pod modified events

setup.py
This adds long_description to PyPI.
https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/
=> adds long_description

task_processing/plugins/kubernetes/kubernetes_pod_executor.py, tests/unit/plugins/kubernetes/kubernetes_pod_executor_test.py
The previous code did not do what we expected and ended up creating
pods with a limit and no request.
=> Only set explicit requests if a value is set 

.github/workflows/ci.yml, .github/workflows/pypi.yml
See https://github.com/actions/runner-images/issues/11101
=> Update runner image to ubuntu-22.04 (Jammy)
